ARG PYTHON_VERSION=3.11
ARG ALPINE_VERSION=3.22
FROM python:${PYTHON_VERSION}-alpine${ALPINE_VERSION} AS base

# Basic files
COPY resources/nginx-template.conf /templates/nginx/frappe.conf.template
COPY resources/nginx-entrypoint.sh /usr/local/bin/nginx-entrypoint.sh

ARG NODE_VERSION=20.19.2
ENV NVM_DIR=/home/frappe/.nvm
ENV PATH=${NVM_DIR}/versions/node/v${NODE_VERSION}/bin/:${PATH}

RUN adduser -D -h /home/frappe -s /bin/bash frappe \
    && apk update && apk add --no-cache \
       bash \
       curl \
       git \
       vim \
       nginx \
       gettext \
       file \
       mesa-gl \
       pango \
       harfbuzz \
       restic \
       gnupg \
       mariadb-client \
       less \
       postgresql-client \
       postgresql-dev \
       jq \
       mime-types \
       # build/runtime helpers for nvm/node
       ca-certificates \
       openssl \
       su-exec \
       libc6-compat \
    && mkdir -p ${NVM_DIR} \
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash \
    && . ${NVM_DIR}/nvm.sh \
    && nvm install ${NODE_VERSION} \
    && nvm use v${NODE_VERSION} \
    && npm install -g yarn \
    && nvm alias default v${NODE_VERSION} \
    && rm -rf ${NVM_DIR}/.cache \
    && echo 'export NVM_DIR="/home/frappe/.nvm"' >>/home/frappe/.bashrc \
    && echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm' >>/home/frappe/.bashrc \
    && echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion' >>/home/frappe/.bashrc \
    # Note: wkhtmltopdf packaging for Alpine varies. Install a packaged/static binary separately if required.
    && pip3 install frappe-bench \
    # Fixes for non-root nginx and logs to stdout
    && sed -i '/user nginx/d' /etc/nginx/nginx.conf || true \
    && ln -sf /dev/stdout /var/log/nginx/access.log && ln -sf /dev/stderr /var/log/nginx/error.log \
    && touch /run/nginx.pid \
    && chown -R frappe:frappe /etc/nginx/conf.d || true \
    && chown -R frappe:frappe /etc/nginx/nginx.conf || true \
    && chown -R frappe:frappe /var/log/nginx || true \
    && chown -R frappe:frappe /var/lib/nginx || true \
    && chown -R frappe:frappe /run/nginx.pid || true \
    && chmod 755 /usr/local/bin/nginx-entrypoint.sh \
    && chmod 644 /templates/nginx/frappe.conf.template \
    && rm -rf /var/cache/apk/*

FROM base AS builder

# build dependencies for Python wheels and native libs
RUN apk update && apk add --no-cache --virtual .build-deps \
      build-base \
      wget \
      cairo-dev \
      pango-dev \
      jpeg-dev \
      giflib-dev \
      librsvg-dev \
      libpq \
      libffi-dev \
      lcms2-dev \
      openldap-dev \
      mariadb-dev \
      cyrus-sasl-dev \
      tiff-dev \
      libwebp-dev \
      pkgconfig \
      redis \
      rlwrap \
      tk-dev \
      cron \
      gcc \
      bzip2-dev \
    && rm -rf /var/cache/apk/*

# apps.json includes
ARG APPS_JSON_BASE64
RUN if [ -n "${APPS_JSON_BASE64}" ]; then \
    mkdir /opt/frappe && echo "${APPS_JSON_BASE64}" | base64 -d > /opt/frappe/apps.json; \
  fi

USER frappe

ARG FRAPPE_BRANCH=version-15
ARG FRAPPE_PATH=https://github.com/frappe/frappe
RUN export APP_INSTALL_ARGS="" && \
  if [ -n "${APPS_JSON_BASE64}" ]; then \
    export APP_INSTALL_ARGS="--apps_path=/opt/frappe/apps.json"; \
  fi && \
  bench init ${APP_INSTALL_ARGS}\
    --frappe-branch=${FRAPPE_BRANCH} \
    --frappe-path=${FRAPPE_PATH} \
    --no-procfile \
    --no-backups \
    --skip-redis-config-generation \
    --verbose \
    /home/frappe/frappe-bench && \
  cd /home/frappe/frappe-bench && \
  echo "{}" > sites/common_site_config.json && \
  find apps -mindepth 1 -path "*/.git" | xargs rm -fr

FROM base AS backend

USER frappe

COPY --from=builder --chown=frappe:frappe /home/frappe/frappe-bench /home/frappe/frappe-bench

RUN /home/frappe/frappe-bench/env/bin/pip3 install "paramiko<4"

WORKDIR /home/frappe/frappe-bench

VOLUME [ \
  "/home/frappe/frappe-bench/sites", \
  "/home/frappe/frappe-bench/sites/assets", \
  "/home/frappe/frappe-bench/logs" \
]

CMD [ \
  "/home/frappe/frappe-bench/env/bin/gunicorn", \
  "--chdir=/home/frappe/frappe-bench/sites", \
  "--bind=0.0.0.0:8000", \
  "--threads=4", \
  "--workers=2", \
  "--worker-class=gthread", \
  "--worker-tmp-dir=/dev/shm", \
  "--timeout=120", \
  "--preload", \
  "frappe.app:application" \
]